# Generated by scripts/gen_config_types.py from mq-bridge.schema.json.
# Do not edit by hand; re-run the generator after changing the schema.

from __future__ import annotations

AggregateEntry = dict
AggregateMiddleware = dict
AmqpConfig = dict
AwsConfig = dict
BufferMiddleware = dict
ClickHouseConfig = dict
CompressionMiddleware = dict
CookieJarMiddleware = dict
CsvConfig = dict
DeadLetterQueueMiddleware = dict
DeduplicationMiddleware = dict
DelayMiddleware = dict
DetailedMappingRule = dict
DirSpoolConfig = dict
EncryptionConfig = dict
Endpoint = dict
FileConfig = dict
GrpcConfig = dict
HttpBulkAuth = dict
HttpBulkAwsSigV4 = dict
HttpBulkConfig = dict
HttpBulkCursor = dict
HttpBulkDelete = dict
HttpBulkItems = dict
HttpBulkJob = dict
HttpBulkLines = dict
HttpBulkOAuth2 = dict
HttpBulkQuery = dict
HttpBulkRead = dict
HttpBulkResult = dict
HttpBulkUpsert = dict
HttpConfig = dict
IbmMqConfig = dict
IbmTlsConfig = dict
KafkaConfig = dict
LimiterMiddleware = dict
LookupEntry = dict
LookupMiddleware = dict
MemoryConfig = dict
MetricsMiddleware = dict
Middleware = dict
MongoDbConfig = dict
MqttConfig = dict
NatsConfig = dict
ObjectStoreConfig = dict
OtelMiddleware = dict
PackMiddleware = dict
PostgresCdcConfig = dict
RandomPanicMiddleware = dict
RedisStreamsConfig = dict
RequestForwardConfig = dict
ResponseConfig = dict
RetryMiddleware = dict
Route = dict
SequenceConfig = dict
SledConfig = dict
SqlxConfig = dict
StreamBufferConfig = dict
SwitchCase = dict
SwitchConfig = dict
TimeoutMiddleware = dict
TlsConfig = dict
TransformMiddleware = dict
UnpackMiddleware = dict
WeakJoinMiddleware = dict
WebSocketConfig = dict
ZeroMqConfig = dict
AggregateConsistency = str
AggregateEmit = str
AggregateOnError = str
CipherKind = str
Compression = str
CsvMismatch = str
CsvNested = str
DatePartitionStyle = str
DeliveryGuarantee = str
FaultMode = str
FileFormat = str
FileFsync = str
FilterMiddleware = str
HttpBulkFormat = str
HttpBulkStream = str
HttpServerProtocol = str
IdHash = str
InputErrorPolicy = str
MappingRule = str
MongoConsume = str
MongoDbFormat = str
MqttProtocol = str
NameBy = str
NatsDeliverPolicy = str
PackFormat = str
PostgresConsume = str
SpoolClaim = str
SpoolDone = str
SpoolFsync = str
SqlColumns = str
SqlTimestamps = str
StaticConfig = str
TransformErrorPolicy = str
WeakJoinAck = str
WeakJoinTimeout = str
WebSocketExecutionMode = str
ZeroMqBackend = str
ZeroMqFormat = str
ZeroMqSocketType = str
RouteConfig = Route
EndpointConfig = Endpoint
RoutesConfig = dict
ConfigDocument = dict

__all__ = [
    "AggregateConsistency",
    "AggregateEmit",
    "AggregateEntry",
    "AggregateMiddleware",
    "AggregateOnError",
    "AmqpConfig",
    "AwsConfig",
    "BufferMiddleware",
    "CipherKind",
    "ClickHouseConfig",
    "Compression",
    "CompressionMiddleware",
    "ConfigDocument",
    "CookieJarMiddleware",
    "CsvConfig",
    "CsvMismatch",
    "CsvNested",
    "DatePartitionStyle",
    "DeadLetterQueueMiddleware",
    "DeduplicationMiddleware",
    "DelayMiddleware",
    "DeliveryGuarantee",
    "DetailedMappingRule",
    "DirSpoolConfig",
    "EncryptionConfig",
    "Endpoint",
    "EndpointConfig",
    "FaultMode",
    "FileConfig",
    "FileFormat",
    "FileFsync",
    "FilterMiddleware",
    "GrpcConfig",
    "HttpBulkAuth",
    "HttpBulkAwsSigV4",
    "HttpBulkConfig",
    "HttpBulkCursor",
    "HttpBulkDelete",
    "HttpBulkFormat",
    "HttpBulkItems",
    "HttpBulkJob",
    "HttpBulkLines",
    "HttpBulkOAuth2",
    "HttpBulkQuery",
    "HttpBulkRead",
    "HttpBulkResult",
    "HttpBulkStream",
    "HttpBulkUpsert",
    "HttpConfig",
    "HttpServerProtocol",
    "IbmMqConfig",
    "IbmTlsConfig",
    "IdHash",
    "InputErrorPolicy",
    "KafkaConfig",
    "LimiterMiddleware",
    "LookupEntry",
    "LookupMiddleware",
    "MappingRule",
    "MemoryConfig",
    "MetricsMiddleware",
    "Middleware",
    "MongoConsume",
    "MongoDbConfig",
    "MongoDbFormat",
    "MqttConfig",
    "MqttProtocol",
    "NameBy",
    "NatsConfig",
    "NatsDeliverPolicy",
    "ObjectStoreConfig",
    "OtelMiddleware",
    "PackFormat",
    "PackMiddleware",
    "PostgresCdcConfig",
    "PostgresConsume",
    "RandomPanicMiddleware",
    "RedisStreamsConfig",
    "RequestForwardConfig",
    "ResponseConfig",
    "RetryMiddleware",
    "Route",
    "RouteConfig",
    "RoutesConfig",
    "SequenceConfig",
    "SledConfig",
    "SpoolClaim",
    "SpoolDone",
    "SpoolFsync",
    "SqlColumns",
    "SqlTimestamps",
    "SqlxConfig",
    "StaticConfig",
    "StreamBufferConfig",
    "SwitchCase",
    "SwitchConfig",
    "TimeoutMiddleware",
    "TlsConfig",
    "TransformErrorPolicy",
    "TransformMiddleware",
    "UnpackMiddleware",
    "WeakJoinAck",
    "WeakJoinMiddleware",
    "WeakJoinTimeout",
    "WebSocketConfig",
    "WebSocketExecutionMode",
    "ZeroMqBackend",
    "ZeroMqConfig",
    "ZeroMqFormat",
    "ZeroMqSocketType",
]
