# Generated by scripts/gen_config_types.py from mq-bridge.schema.json.
# Do not edit by hand; re-run the generator after changing the schema.
from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from typing_extensions import Required, TypedDict


class AmqpConfig(TypedDict, total=False):
    """General AMQP connection configuration."""
    delayed_ack: bool
    exchange: Optional[str]
    no_declare_queue: bool
    no_persistence: bool
    password: Optional[str]
    prefetch_count: Optional[int]
    queue: Optional[str]
    source_metadata: bool
    subscribe_mode: bool
    tls: TlsConfig
    url: Required[str]
    username: Optional[str]


class AwsConfig(TypedDict, total=False):
    access_key: Optional[str]
    binary_payload_mode: bool
    endpoint_url: Optional[str]
    max_messages: Optional[int]
    queue_url: Optional[str]
    region: Optional[str]
    secret_key: Optional[str]
    session_token: Optional[str]
    topic_arn: Optional[str]
    wait_time_seconds: Optional[int]


class BufferMiddleware(TypedDict, total=False):
    """Publisher-side buffer middleware configuration."""
    max_delay_ms: Required[int]
    max_messages: Required[int]


class ClickHouseConfig(TypedDict, total=False):
    """ClickHouse endpoint configuration (talks the ClickHouse HTTP interface)."""
    async_insert: bool
    checkpoint_store: Optional[str]
    columns: Optional[Dict[str, str]]
    compression: Compression
    connect_timeout_ms: Optional[int]
    cursor_column: Optional[str]
    cursor_id: Optional[str]
    database: Optional[str]
    max_polling_interval_ms: Optional[int]
    password: Optional[str]
    polling_interval_ms: Optional[int]
    request_timeout_ms: Optional[int]
    select_columns: Optional[str]
    table: Required[str]
    tls: TlsConfig
    url: Required[str]
    username: Optional[str]
    wait_for_async_insert: Optional[bool]


class CompressionMiddleware(TypedDict, total=False):
    """Payload-compression middleware configuration."""
    algorithm: Compression
    max_decompressed_bytes: Optional[int]


class CookieJarMiddleware(TypedDict, total=False):
    """Cookie/session jar middleware configuration."""
    capture_metadata_keys: List[str]
    cookie_metadata_key: str
    export_metadata_prefix: Optional[str]
    inject_metadata: Dict[str, str]
    max_cookies: int
    set_cookie_metadata_key: str
    shared_scope: Optional[str]


class DeadLetterQueueMiddleware(TypedDict, total=False):
    """Dead-Letter Queue (DLQ) middleware configuration."""
    endpoint: Required[Endpoint]


class DeduplicationMiddleware(TypedDict, total=False):
    """Deduplication middleware configuration."""
    key: Optional[str]
    sled_path: Optional[str]
    store: Optional[str]
    ttl_seconds: Required[int]


class DelayMiddleware(TypedDict, total=False):
    """Delay middleware configuration."""
    delay_ms: Required[int]


class DetailedMappingRule(TypedDict, total=False):
    """Full mapping form with a fallback value and/or a presence requirement."""
    default: Any
    path: Required[str]
    required: bool


class DirSpoolConfig(TypedDict, total=False):
    """Configuration for a `dir_spool` endpoint: a crash-safe FIFO queue backed by a directory."""
    atomic: bool
    claim: SpoolClaim
    consumer_file: str
    done_file: str
    drain_on_read: bool
    emit_done: SpoolDone
    fsync: SpoolFsync
    metadata_extension: str
    naming_pattern: str
    path: Required[str]
    payload_extension: str
    poll_interval_ms: int
    producer_file: str
    shard_depth: int
    shard_width: int
    source_metadata: bool
    stop_on_done: bool


class EncryptionConfig(TypedDict, total=False):
    """AEAD encryption settings, shared by the `encryption` middleware (per-message"""
    authenticate_metadata: List[str]
    cipher: CipherKind
    decrypt_keys: Dict[str, str]
    key: Required[str]
    key_id: str


class Endpoint(TypedDict, total=False):
    """Represents a connection point for messages, which can be a source (input) or a sink (output)."""
    amqp: AmqpConfig
    aws: AwsConfig
    clickhouse: ClickHouseConfig
    custom: Dict[str, Any]
    dir_spool: DirSpoolConfig
    fanout: List[Endpoint]
    file: FileConfig
    grpc: GrpcConfig
    http: HttpConfig
    ibmmq: IbmMqConfig
    kafka: KafkaConfig
    memory: MemoryConfig
    middlewares: List[Middleware]
    mongodb: MongoDbConfig
    mqtt: MqttConfig
    nats: NatsConfig
    null: Any
    object_store: ObjectStoreConfig
    postgres_cdc: PostgresCdcConfig
    reader: Endpoint
    redis_streams: RedisStreamsConfig
    ref: str
    request: RequestForwardConfig
    response: ResponseConfig
    sequence: SequenceConfig
    sled: SledConfig
    sqlx: SqlxConfig
    static: StaticConfig
    stream_buffer: StreamBufferConfig
    switch: SwitchConfig
    websocket: WebSocketConfig
    zeromq: ZeroMqConfig


class FileConfig(TypedDict, total=False):
    compression: Compression
    delimiter: Optional[str]
    encryption: Optional[EncryptionConfig]
    format: FileFormat
    idempotency: Optional[bool]
    name_by: NameBy
    path: Required[str]
    source_metadata: bool


class GrpcConfig(TypedDict, total=False):
    api_key: Optional[str]
    api_key_name: Optional[str]
    bearer_token: Optional[str]
    binary_metadata: Dict[str, List[int]]
    concurrency_limit_per_connection: Optional[int]
    connect_timeout_ms: Optional[int]
    consumer_id: Optional[str]
    descriptor_set_bytes: Optional[List[int]]
    descriptor_set_path: Optional[str]
    http2_keepalive_interval_ms: Optional[int]
    http2_keepalive_timeout_ms: Optional[int]
    idle_stream_timeout_ms: Optional[int]
    initial_connection_window_size: Optional[int]
    initial_stream_window_size: Optional[int]
    max_decoding_message_size: Optional[int]
    max_encoding_message_size: Optional[int]
    metadata: Dict[str, str]
    method_name: Optional[str]
    overall_timeout_ms: Optional[int]
    reflection: bool
    request: Any
    request_timeout_ms: Optional[int]
    server_mode: bool
    server_streaming: bool
    service_name: Optional[str]
    shared: Optional[bool]
    timeout_ms: Optional[int]
    tls: TlsConfig
    topic: Optional[str]
    url: Required[str]


class HttpConfig(TypedDict, total=False):
    """General HTTP connection configuration."""
    basic_auth: Optional[List[Any]]
    batch_concurrency: Optional[int]
    compression: Compression
    compression_enabled: Optional[bool]
    compression_threshold_bytes: Optional[int]
    concurrency_limit: Optional[int]
    custom_headers: Dict[str, str]
    fire_and_forget: bool
    inline_response_fast_path: Optional[bool]
    internal_buffer_size: Optional[int]
    message_id_header: Optional[str]
    method: Optional[str]
    pass_through_status: bool
    path: Optional[str]
    pool_idle_timeout_ms: Optional[int]
    receive_streamable: bool
    request_timeout_ms: Optional[int]
    server_protocol: HttpServerProtocol
    shared: Optional[bool]
    stream_response_to: Optional[Endpoint]
    tcp_keepalive_ms: Optional[int]
    tls: TlsConfig
    url: Required[str]
    workers: Optional[int]


class IbmMqConfig(TypedDict, total=False):
    """Connection settings for the IBM MQ Queue Manager."""
    channel: Required[str]
    disable_status_inq: bool
    internal_buffer_size: Optional[int]
    max_message_size: int
    password: Optional[str]
    queue: Optional[str]
    queue_manager: Required[str]
    tls: IbmTlsConfig
    topic: Optional[str]
    url: Required[str]
    username: Optional[str]
    wait_timeout_ms: int


class IbmTlsConfig(TypedDict, total=False):
    """TLS configuration for the IBM MQ native client."""
    accept_invalid_certs: bool
    cert_file: Optional[str]
    cert_password: Optional[str]
    cipher_spec: Optional[str]
    key_repository: Optional[str]
    key_repository_password: Optional[str]
    required: bool


class KafkaConfig(TypedDict, total=False):
    """General Kafka connection configuration."""
    consumer_options: Optional[List[List[Any]]]
    delayed_ack: bool
    group_id: Optional[str]
    partition_key: Optional[str]
    partitions: Optional[int]
    password: Optional[str]
    producer_options: Optional[List[List[Any]]]
    shared: Optional[bool]
    source_metadata: bool
    tls: TlsConfig
    topic: Optional[str]
    url: Required[str]
    username: Optional[str]


class LimiterMiddleware(TypedDict, total=False):
    """Throughput limiter middleware configuration."""
    messages_per_second: Required[float]


class MemoryConfig(TypedDict, total=False):
    capacity: Optional[int]
    enable_nack: bool
    request_reply: bool
    request_timeout_ms: Optional[int]
    subscribe_mode: bool
    topic: str
    url: str


class MetricsMiddleware(TypedDict, total=False):
    """Metrics middleware configuration."""
    pass


class Middleware(TypedDict, total=False):
    """An enumeration of all supported middleware types."""
    buffer: BufferMiddleware
    compression: CompressionMiddleware
    cookie_jar: CookieJarMiddleware
    custom: Dict[str, Any]
    deduplication: DeduplicationMiddleware
    delay: DelayMiddleware
    dlq: DeadLetterQueueMiddleware
    encryption: EncryptionConfig
    filter: str
    id: str
    limiter: LimiterMiddleware
    metrics: MetricsMiddleware
    pack: PackMiddleware
    random_panic: RandomPanicMiddleware
    retry: RetryMiddleware
    transform: TransformMiddleware
    unpack: UnpackMiddleware
    weak_join: WeakJoinMiddleware


class MongoDbConfig(TypedDict, total=False):
    """General MongoDB connection configuration."""
    capped_size_bytes: Optional[int]
    change_stream: bool
    checkpoint_store: Optional[str]
    collection: Optional[str]
    consume: Optional[MongoConsume]
    cursor_id: Optional[str]
    database: Required[str]
    format: MongoDbFormat
    id_field: Optional[str]
    meta_collection: Optional[str]
    password: Optional[str]
    polling_interval_ms: Optional[int]
    receive_query: Optional[str]
    reply_polling_ms: Optional[int]
    report_outcome: bool
    request_reply: bool
    request_timeout_ms: Optional[int]
    shared: Optional[bool]
    source_metadata: bool
    tls: TlsConfig
    ttl_seconds: Optional[int]
    url: Required[str]
    username: Optional[str]


class MqttConfig(TypedDict, total=False):
    """General MQTT connection configuration."""
    clean_session: bool
    client_id: Optional[str]
    delayed_ack: bool
    keep_alive_seconds: Optional[int]
    max_inflight: Optional[int]
    password: Optional[str]
    protocol: MqttProtocol
    qos: Optional[int]
    queue_capacity: Optional[int]
    session_expiry_interval: Optional[int]
    tls: TlsConfig
    topic: Optional[str]
    url: Required[str]
    username: Optional[str]


class NatsConfig(TypedDict, total=False):
    """General NATS connection configuration."""
    deduplicate: bool
    delayed_ack: bool
    deliver_policy: Optional[NatsDeliverPolicy]
    no_jetstream: bool
    password: Optional[str]
    prefetch_count: Optional[int]
    request_reply: bool
    request_timeout_ms: Optional[int]
    shared: Optional[bool]
    source_metadata: bool
    stream: Optional[str]
    stream_max_bytes: Optional[int]
    stream_max_messages: Optional[int]
    subject: Optional[str]
    subscriber_mode: bool
    tls: TlsConfig
    token: Optional[str]
    url: Required[str]
    username: Optional[str]


class ObjectStoreConfig(TypedDict, total=False):
    """Configuration for a local or cloud object-store endpoint."""
    checkpoint_store: Optional[str]
    compression: Compression
    cursor_id: Optional[str]
    date_partition: Optional[bool]
    delimiter: Optional[str]
    encryption: Optional[EncryptionConfig]
    extension: Optional[str]
    format: FileFormat
    idempotency: Optional[bool]
    max_object_bytes: Optional[int]
    name_by: NameBy
    polling_interval_ms: Optional[int]
    url: Required[str]


class PackMiddleware(TypedDict, total=False):
    """Transport batching middleware configuration (`pack`, output side)."""
    drop_message_id: bool
    format: PackFormat
    max_bytes: int
    max_messages: int


class PostgresCdcConfig(TypedDict, total=False):
    """Postgres logical-replication CDC source (pgoutput). Source-only."""
    checkpoint_store: Optional[str]
    create_publication: bool
    create_slot: bool
    cursor_id: Optional[str]
    publication: Required[str]
    publication_tables: List[str]
    slot_name: str
    source_metadata: bool
    status_interval_ms: int
    temporary_slot: bool
    tls: TlsConfig
    url: Required[str]


class RandomPanicMiddleware(TypedDict, total=False):
    """Middleware for fault injection testing."""
    enabled: bool
    mode: FaultMode
    trigger_on_message: Optional[int]


class RedisStreamsConfig(TypedDict, total=False):
    """Configuration for a Redis Streams endpoint."""
    approx_trim: Optional[bool]
    block_ms: Optional[int]
    consumer_name: Optional[str]
    group: Optional[str]
    internal_buffer_size: Optional[int]
    maxlen: Optional[int]
    password: Optional[str]
    read_from_start: bool
    reader_connections: Optional[int]
    redelivery_timeout_ms: Optional[int]
    stream: Optional[str]
    subscriber_mode: bool
    url: Required[str]
    username: Optional[str]


class RequestForwardConfig(TypedDict, total=False):
    """Sends each message to a request-capable endpoint and forwards its response elsewhere."""
    forward_to: Required[Endpoint]
    to: Required[Endpoint]


class ResponseConfig(TypedDict, total=False):
    pass


class RetryMiddleware(TypedDict, total=False):
    """Retry middleware configuration."""
    initial_interval_ms: int
    max_attempts: int
    max_interval_ms: int
    multiplier: float


class Route(TypedDict, total=False):
    """Defines a single message processing route from an input to an output."""
    allow_fault_injection: bool
    batch_size: int
    commit_concurrency_limit: int
    concurrency: int
    description: str
    empty_batch_delay_ms: int
    exit_on_empty: bool
    input: Required[Endpoint]
    output: Optional[Endpoint]
    reconnect_interval_ms: int
    startup_timeout_ms: int


class SequenceConfig(TypedDict, total=False):
    """Reads several input endpoints one after another: each is drained before the next"""
    checkpoint_store: Optional[str]
    cursor_id: Optional[str]
    endpoints: Required[List[Endpoint]]


class SledConfig(TypedDict, total=False):
    """General Sled database configuration"""
    delete_after_read: bool
    path: Required[str]
    read_from_start: bool
    tree: Optional[str]


class SqlxConfig(TypedDict, total=False):
    """General SQLx connection configuration."""
    acquire_timeout_ms: Optional[int]
    auto_create_table: bool
    bulk_copy: bool
    checkpoint_store: Optional[str]
    create_publication: bool
    cursor_column: Optional[str]
    cursor_id: Optional[str]
    delete_after_read: bool
    idle_timeout_ms: Optional[int]
    insert_query: Optional[str]
    max_connections: Optional[int]
    max_lifetime_ms: Optional[int]
    max_polling_interval_ms: Optional[int]
    min_connections: Optional[int]
    password: Optional[str]
    polling_interval_ms: Optional[int]
    publication: Optional[str]
    select_query: Optional[str]
    shared: Optional[bool]
    slot_name: Optional[str]
    source_metadata: bool
    table: Required[str]
    test_before_acquire: Optional[bool]
    tls: TlsConfig
    url: Required[str]
    username: Optional[str]


class StreamBufferConfig(TypedDict, total=False):
    """Configuration for the correlated in-process stream response buffer."""
    capacity: Optional[int]
    correlation_id: Optional[str]
    idle_ttl_secs: Optional[int]
    topic: Required[str]


# One predicate case of a `switch` in `when` mode.
SwitchCase = TypedDict(
    "SwitchCase",
    {
        "if": Required[str],
        "to": Required[Endpoint],
    },
    total=False,
)


class SwitchConfig(TypedDict, total=False):
    cases: Dict[str, Endpoint]
    default: Optional[Endpoint]
    metadata_key: str
    when: List[SwitchCase]


class TlsConfig(TypedDict, total=False):
    """TLS configuration for secure connections."""
    accept_invalid_certs: bool
    ca_file: Optional[str]
    cert_file: Optional[str]
    cert_password: Optional[str]
    key_file: Optional[str]
    required: bool


class TransformMiddleware(TypedDict, total=False):
    """JSON transform middleware configuration."""
    apply_defaults: bool
    coerce: bool
    coerce_empty_as_null: bool
    expression: Optional[str]
    mapping: Dict[str, MappingRule]
    on_error: TransformErrorPolicy
    schema: Any
    schema_file: Optional[str]


class UnpackMiddleware(TypedDict, total=False):
    """Transport batching middleware configuration (`unpack`, input side)."""
    format: PackFormat
    max_messages: Optional[int]


class WeakJoinMiddleware(TypedDict, total=False):
    """Weak Join middleware configuration."""
    branch_by: Optional[str]
    expected_count: Required[int]
    group_by: Required[str]
    on_timeout: WeakJoinTimeout
    required: List[str]
    timeout_ms: Required[int]


class WebSocketConfig(TypedDict, total=False):
    """WebSocket connection configuration."""
    backlog: Optional[int]
    execution_mode: WebSocketExecutionMode
    message_id_header: Optional[str]
    path: Optional[str]
    routed_queue_capacity: Optional[int]
    url: Required[str]


class ZeroMqConfig(TypedDict, total=False):
    backend: ZeroMqBackend
    bind: bool
    format: ZeroMqFormat
    internal_buffer_size: Optional[int]
    request_timeout_ms: Optional[int]
    socket_type: Optional[ZeroMqSocketType]
    topic: Optional[str]
    url: Required[str]


CipherKind = Literal["xchacha20poly1305", "aes256gcm"]
Compression = Literal["none", "gzip", "lz4", "zstd"]
FaultMode = Literal["panic", "disconnect", "timeout", "json_format_error", "nack"]
FileFormat = Literal["normal", "json", "text", "raw", "csv"]
HttpServerProtocol = Literal["auto", "http1_only", "http2_only"]
MappingRule = Union[str, DetailedMappingRule]
MongoConsume = Literal["consumer", "snapshot", "capture_new", "capture_all"]
MongoDbFormat = Literal["normal", "json", "text", "raw"]
MqttProtocol = Literal["v5", "v3"]
NameBy = Literal["auto", "source_position", "write_time"]
NatsDeliverPolicy = Literal["all", "last", "new", "last_per_subject"]
PackFormat = Literal["mqb", "benthos_binary"]
SpoolClaim = Literal["exclusive", "warn", "off"]
SpoolDone = Literal["never", "success", "end"]
SpoolFsync = Literal["chunk", "off"]
StaticConfig = Union[str, Dict[str, Any]]
TransformErrorPolicy = Literal["reject", "pass_through"]
WeakJoinTimeout = Literal["fire", "discard"]
WebSocketExecutionMode = Literal["auto", "direct_only", "routed"]
ZeroMqBackend = Union[Literal["zmq", "omq"], Literal["try_omq"]]
ZeroMqFormat = Literal["json", "raw", "raw_framed"]
ZeroMqSocketType = Literal["push", "pull", "pub", "sub", "req", "rep"]


RouteConfig = Route
EndpointConfig = Endpoint
RoutesConfig = Dict[str, Route]

class ConfigDocument(TypedDict, total=False):
    """Top-level config accepted by from_file / from_str / from_config."""
    routes: Dict[str, Route]
    publishers: Dict[str, Endpoint]
