# Generated by scripts/gen_config_types.py from mq-bridge.schema.json.
# Do not edit by hand; re-run the generator after changing the schema.

from __future__ import annotations

AmqpConfig = dict
AwsConfig = dict
BufferMiddleware = dict
ClickHouseConfig = dict
CompressionMiddleware = dict
CookieJarMiddleware = dict
DeadLetterQueueMiddleware = dict
DeduplicationMiddleware = dict
DelayMiddleware = dict
DetailedMappingRule = dict
DirSpoolConfig = dict
EncryptionConfig = dict
Endpoint = dict
FileConfig = dict
GrpcConfig = dict
HttpConfig = dict
IbmMqConfig = dict
IbmTlsConfig = dict
KafkaConfig = dict
LimiterMiddleware = dict
MemoryConfig = dict
MetricsMiddleware = dict
Middleware = dict
MongoDbConfig = dict
MqttConfig = dict
NatsConfig = dict
ObjectStoreConfig = dict
PackMiddleware = dict
PostgresCdcConfig = dict
RandomPanicMiddleware = dict
RedisStreamsConfig = dict
RequestForwardConfig = dict
ResponseConfig = dict
RetryMiddleware = dict
Route = dict
SequenceConfig = dict
SledConfig = dict
SqlxConfig = dict
StreamBufferConfig = dict
SwitchCase = dict
SwitchConfig = dict
TlsConfig = dict
TransformMiddleware = dict
UnpackMiddleware = dict
WeakJoinMiddleware = dict
WebSocketConfig = dict
ZeroMqConfig = dict
CipherKind = str
Compression = str
FaultMode = str
FileFormat = str
HttpServerProtocol = str
MappingRule = str
MongoConsume = str
MongoDbFormat = str
MqttProtocol = str
NameBy = str
NatsDeliverPolicy = str
PackFormat = str
PostgresConsume = str
SpoolClaim = str
SpoolDone = str
SpoolFsync = str
StaticConfig = str
TransformErrorPolicy = str
WeakJoinTimeout = str
WebSocketExecutionMode = str
ZeroMqBackend = str
ZeroMqFormat = str
ZeroMqSocketType = str
RouteConfig = Route
EndpointConfig = Endpoint
RoutesConfig = dict
ConfigDocument = dict

__all__ = [
    "AmqpConfig",
    "AwsConfig",
    "BufferMiddleware",
    "CipherKind",
    "ClickHouseConfig",
    "Compression",
    "CompressionMiddleware",
    "ConfigDocument",
    "CookieJarMiddleware",
    "DeadLetterQueueMiddleware",
    "DeduplicationMiddleware",
    "DelayMiddleware",
    "DetailedMappingRule",
    "DirSpoolConfig",
    "EncryptionConfig",
    "Endpoint",
    "EndpointConfig",
    "FaultMode",
    "FileConfig",
    "FileFormat",
    "GrpcConfig",
    "HttpConfig",
    "HttpServerProtocol",
    "IbmMqConfig",
    "IbmTlsConfig",
    "KafkaConfig",
    "LimiterMiddleware",
    "MappingRule",
    "MemoryConfig",
    "MetricsMiddleware",
    "Middleware",
    "MongoConsume",
    "MongoDbConfig",
    "MongoDbFormat",
    "MqttConfig",
    "MqttProtocol",
    "NameBy",
    "NatsConfig",
    "NatsDeliverPolicy",
    "ObjectStoreConfig",
    "PackFormat",
    "PackMiddleware",
    "PostgresCdcConfig",
    "PostgresConsume",
    "RandomPanicMiddleware",
    "RedisStreamsConfig",
    "RequestForwardConfig",
    "ResponseConfig",
    "RetryMiddleware",
    "Route",
    "RouteConfig",
    "RoutesConfig",
    "SequenceConfig",
    "SledConfig",
    "SpoolClaim",
    "SpoolDone",
    "SpoolFsync",
    "SqlxConfig",
    "StaticConfig",
    "StreamBufferConfig",
    "SwitchCase",
    "SwitchConfig",
    "TlsConfig",
    "TransformErrorPolicy",
    "TransformMiddleware",
    "UnpackMiddleware",
    "WeakJoinMiddleware",
    "WeakJoinTimeout",
    "WebSocketConfig",
    "WebSocketExecutionMode",
    "ZeroMqBackend",
    "ZeroMqConfig",
    "ZeroMqFormat",
    "ZeroMqSocketType",
]
